name: flutter_beautyshop_challenge
description: A Flutter UI Challenge.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-126.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_staggered_grid_view: ^0.6.0

flutter:

  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Falling Sky
      fonts:
        - asset: fonts/fallingsky.otf
        - asset: fonts/fallingskybd.otf
        - asset: fonts/fallingskylight.otf